# Generated by Django 4.0.3 on 2022-03-29 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('course_subject', models.CharField(max_length=5)),
                ('course_number', models.CharField(max_length=5)),
                ('course_roster', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
