# Generated by Django 4.0.4 on 2022-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='num_alerts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
