# Generated by Django 4.0.4 on 2022-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_alerts',
            field=models.IntegerField(default=0),
        ),
    ]
