# Generated by Django 4.0.3 on 2022-03-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses_enrolled',
        ),
    ]
