# Generated by Django 4.0.4 on 2022-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='event_id',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
