# Generated by Django 4.0.4 on 2022-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0002_userprofile_num_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(max_length=1000),
        ),
    ]
