# Generated by Django 4.0.3 on 2022-03-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0003_remove_customuser_courses_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses_enrolled',
            field=models.ManyToManyField(to='studysite.course'),
        ),
    ]
