# Generated by Django 4.0.4 on 2022-05-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0003_alter_message_msg_content'),
        ('studysite', '0003_studyevent_event_id_alter_contactus_question'),
    ]

    operations = [
    ]
