# Generated by Django 4.0.2 on 2022-04-11 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0006_studyevent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='studyevent',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
