# Generated by Django 4.0.2 on 2022-04-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studysite', '0008_remove_studyevent_course_studyevent_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studysite.course'),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
