# Generated by Django 4.0.2 on 2022-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0009_alter_studyevent_course_alter_studyevent_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='users',
            field=models.ManyToManyField(blank=True, to='studysite.UserProfile'),
        ),
    ]
